# Generated by Django 4.1.5 on 2023-12-03 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('fecha_incorporacion', models.DateField()),
                ('año_nacimiento', models.IntegerField()),
                ('telefono', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('sexo', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Otro', 'Otro')], max_length=50)),
                ('estado', models.CharField(choices=[('Vigente', 'Vigente'), ('Inactivo', 'Inactivo'), ('Suspendido', 'Suspendido')], max_length=50)),
                ('observacion', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
