# Generated by Django 4.1.5 on 2023-12-03 01:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Socios_APP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='telefono',
            field=models.CharField(max_length=12, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(12)]),
        ),
    ]
