# Generated by Django 4.1.5 on 2023-12-03 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Socios_APP', '0002_alter_socio_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='año_nacimiento',
            field=models.IntegerField(max_length=4),
        ),
    ]
